version: '3.8'
services:
  tagspaces:
    image: 'tagspaces'
    container_name: tagspaces-docker
    build:
      context: tagspaces-docker
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
